### ISSUE TITLE
where is the excel file MaterialList.xlsx?

### ISSUE THREAD

**Issue by samyuchao** [jeremytammik/AddMaterials#5]
Can not find the file MaterialList.xlsx

**Comment by jeremytammik** [comment]
Read the blog post: http://thebuildingcoder.typepad.com/blog/2014/03/adding-new-materials-from-list-updated-again.html

It includes a link.

Oh dear, I checked for you, and it does not. 

Still the file is available on The Building Coder blog GitHub repository `tbc` under

https://github.com/jeremytammik/tbc/tree/gh-pages/a/zip/MaterialList.xlsx
